// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLqcsqSOBKTd5htLEak5o058yg1bEkqQ',
    appId: '1:384753682102:web:a56966ec44fa34020c8817',
    messagingSenderId: '384753682102',
    projectId: 'voting-application-f5eb5',
    authDomain: 'voting-application-f5eb5.firebaseapp.com',
    storageBucket: 'voting-application-f5eb5.appspot.com',
    measurementId: 'G-3G8YPX1KZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5pXf8UsPkhA-HqhVzuEOOnuOoMBw_Jg',
    appId: '1:384753682102:android:a3223270f7f117460c8817',
    messagingSenderId: '384753682102',
    projectId: 'voting-application-f5eb5',
    storageBucket: 'voting-application-f5eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4irZTIba6mJ6nmWs4xZFJjOpV0eA-bE',
    appId: '1:384753682102:ios:e06686cedcf9d88e0c8817',
    messagingSenderId: '384753682102',
    projectId: 'voting-application-f5eb5',
    storageBucket: 'voting-application-f5eb5.appspot.com',
    iosClientId: '384753682102-poi1dn227ptqcfv9pcmvak38vik2fm0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv4irZTIba6mJ6nmWs4xZFJjOpV0eA-bE',
    appId: '1:384753682102:ios:e06686cedcf9d88e0c8817',
    messagingSenderId: '384753682102',
    projectId: 'voting-application-f5eb5',
    storageBucket: 'voting-application-f5eb5.appspot.com',
    iosClientId: '384753682102-poi1dn227ptqcfv9pcmvak38vik2fm0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.votingApp',
  );
}
